app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask import current_app, request
from . import db, login_manager
from datetime import datetime
from flask_login import UserMixin
import hashlib

@login_manager.user_loader
def load_user(user_id):
	return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = 'users'

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        if self.email is not None and self.avatar_hash is None:
            self.avatar_hash = self.get_avatar()

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), unique=True)
    email = db.Column(db.String(128), unique=True)
    pass_hash = db.Column(db.String(256), nullable=False)
    location = db.Column(db.String(128), nullable=False)
    avatar_hash = db.Column(db.String(128))
    profile_pic = db.Column(db.String(128))
    country = db.Column(db.String(128))
    role = db.Column(db.String(32), nullable=False)
    products = db.relationship('Product', backref='user', lazy='dynamic', cascade="all, delete")
    carts = db.relationship('Cart', backref='owner', lazy='dynamic', cascade="all, delete")

    @property
    def password(self):
        raise AttributeError("Password not readable")

    @password.setter
    def password(self, password):
        self.pass_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_hash, password)

    def get_avatar(self, size=100, default='identicon', rating='g'):
        if request.is_secure:
            url = 'https://secure.gravatar.com/avatar'
        else:
            url = 'http://www.gravatar.com/avatar'
        hash = hashlib.md5(self.email.encode('utf-8')).hexdigest()
        return '{url}/{hash}?s={size}&d={default}&r={rating}'.format(url=url, hash=hash, size=size, default=default, rating=rating)

class Product(db.Model):
    __tablename__ = 'products'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), nullable=False)
    description = db.Column(db.Text)
    category = db.Column(db.String(32))
    price = db.Column(db.Integer, nullable=False)
    image_link = db.Column(db.String(128))
    quantity = db.Column(db.Integer, nullable=False)
    unit = db.Column(db.String(32), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    cart_on = db.relationship('Cart', backref='product', lazy='dynamic', cascade="all, delete")

class Cart(db.Model):
    __tablename__ = 'carts'
    id = db.Column(db.Integer, primary_key=True)
    quantity = db.Column(db.Integer)
    product_id = db.Column(db.Integer, db.ForeignKey('products.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

app/__init__.py
from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config

db = SQLAlchemy()
login_manager = LoginManager()

login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app = Flask(__name__, static_folder="statics")
    app.config.from_object(config[config_name])

    config[config_name].init_app(app)

    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    from .auth import auth as auth_blueprint

    app.register_blueprint(main_blueprint)
    app.add_url_rule('/', endpoint='index')
    app.register_blueprint(auth_blueprint)

    @app.route('/hello')
    def hello():
        return '<h2>Hello world. This is Green Grocer</h2>'

    @app.errorhandler(500)
    def handle_500(e):
        return render_template('500.html'), 500

    @app.errorhandler(404)
    def handle_404(e):
        return render_template('404.html'), 404
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint("main", __name__)

from . import views

app/main/views.py
from . import main
from flask import render_template, request, current_app, jsonify, url_for, redirect, flash
from flask_login import login_required, current_user
# import cloudinary
# from cloudinary.uploader import upload
from ..models import Product, Cart, User
from .. import db
import os
from sqlalchemy import or_, and_, func


@main.route("/", methods=['GET'])
def home():
    return render_template('index.html')

@main.route("/add_product", methods=['GET', 'POST'])
@login_required
def add_product():
    if request.method == 'POST':
        name = request.form.get('name')
        price = request.form.get('price')
        units = request.form.get('units')
        category = request.form.get('category')
        unit = request.form.get('units_specific')
        # thumbnail = request.form.get('image')
        description = request.form.get('description')

        product = Product(name=name, price=price, quantity=units, category=category, unit=unit, description=description, user_id=current_user.id)
        db.session.add(product)
        db.session.commit()

        flash('Product added successfully')
        return redirect(url_for('main.user_products', id=current_user.id))

    return render_template('add_product.html')

# def upload_file(image):
#     current_app.logger.info('in upload route')

#     cloudinary.config(cloud_name = os.getenv('CLOUD_NAME'), api_key=os.getenv('API_KEY'), api_secret=os.getenv('API_SECRET'))
#     upload_result = None

#     current_app.logger.info('%s file_to_upload', image)

#     if image:
#         upload_result = upload(image)
#         current_app.logger.info(upload_result)
#         return jsonify(upload_result)

@main.route("/products", methods=['GET', 'POST'])
@login_required
def products():
    products = None
    users = User.query.with_entities(User.location).distinct()

    if request.method == 'POST':
        key_term_search = request.form.get('keyword_search')
        location_filter = request.form.get('location_filter')
        # cost_filter = request.form.get('cost_filter') or 0
        category_filter = request.form.get('category_filter')

        products = Product.query.join(User).filter(and_(func.lower(Product.name).like("%" + func.lower(key_term_search) + "%"), func.lower(User.location).like("%" + func.lower(location_filter) + "%"),  func.lower(Product.category).like("%" + func.lower(category_filter) + "%"))).all()     

        return render_template("products.html", products=products, users=users)

    products = Product.query.all()
    return render_template("products.html", products=products, users=users)

@main.route("/<int:id>/products", methods=['GET'])
@login_required
def user_products(id):
    products = current_user.products
    return render_template("user_products.html", products=products)

@main.route("/products/<int:id>/remove", methods=['GET'])
def remove_product(id):
    product = Product.query.get(id)
    if not product:
        flash('Product does not exist')
        return redirect(url_for('main.user_products', id=current_user.id))

    db.session.delete(product)
    db.session.commit()
    flash('Product removed successfully')
    return redirect(url_for('main.user_products', id=current_user.id))

@main.route("/<int:id>/cart", methods=['GET', 'POST'])
@login_required
def cart(id):
    if request.method == 'POST':
        quantity = request.form.get('quantity')
        new_product = Cart(quantity=quantity, product_id=id, user_id=current_user.id)
        db.session.add(new_product)
        db.session.commit()
        
        flash('Product added to cart')
        return redirect(url_for('main.products'))

    carts = Cart.query.filter_by(user_id=current_user.id).all()
    return render_template("cart.html", carts=carts)

@main.route("/cart/remove/<int:id>", methods=["GET"])
def remove_cart(id):
    cart = Cart.query.get(id)
    db.session.delete(cart)
    db.session.commit()

    return redirect(url_for('main.cart', id=current_user.id))

app/templates/add_product.html
{% extends 'template.html' %}

{% block title %} Add new products {% endblock %}

{% block body %}
	<!-- <h2>You can add a product here and it will be recorded to our DB</h2> -->
	<div class="prod_form">
		<form action="{{url_for('main.add_product')}}" method="POST">
			<p><input type="text" name="name" id="name" required placeholder="Product name"></p>
			<p><input type="number" name="price" id="price" required placeholder="Product price"></p>
			<p><input type="number" name="units" id="units" required placeholder="Available units">
			<select name="units_specific" id="units_specific" required>
				<option selected value="none">Select a measurement</option>
				<option value="Kg(s)">Kilogram(s)</option>
				<option value="Ltr(s)">Litre(s)</option>
			</select></p>
			<p>Product thumbnail:</p>
			<p><input disabled type="file" name="image" id="image" accept="image/*"></p>
			<p><select name="category" id="category" required>
				<option selected value="none">Select product category</option>
				<option value="animals">Animal products</option>
				<option value="plants">Plant products</option>
				<option value="equipments">Agricultural equipments</option>
			</select></p>
			<p><textarea name="description" id="description" required cols="30" rows="10">Enter short product description</textarea></p>
			<p><button>Add product</button></p>
		</form>
	</div>
{% endblock %}

app/templates/cart.html
{% extends 'template.html' %}

{% block title %} Your cart {% endblock %}

{% block body %}
	<!-- <h2>Manage your shoping cart right here</h2> -->
	{% if carts %}
		<div class="products">
			{% for cart in carts %}
				<div class="prod_cart">
					<h3>{{cart.product.name}}</h3>
					<p class="prod_description">{{cart.product.description}}</p>
					<h6>Unit price: {{cart.product.price}}$ | Qt: {{cart.quantity}} {{cart.product.unit}}</h6>
					<h6>Total price: {{ cart.quantity * cart.product.price }}Ksh</h6>
					<p><a href="{{url_for('main.remove_cart', id=cart.id)}}"><button>Remove from cart</button></a></p>
					<div class="owner_details">
						<p>From: {{cart.product.user.name}}</p>
						<img src="{{cart.product.user.avatar_hash}}" width="20px" alt="">
					</div>
				</div>
			{% endfor %}
		</div>
		<div class="checkout">
			<button disabled>Check out</button>
		</div>
	{% else %}
		<h2>Your shopping cart is empty</h2>
	{% endif %}
{% endblock %}

app/templates/index.html
{% extends 'template.html' %}

{% block title %} Home page {% endblock %}

{% block body %}
	<div class="main_card">
		<h2>What do we do?</h2>
		<p>We create a connection between farmers and potential buyers. Green Grocer is a platform where you get to access products from Kenya’s best farms and get to sell your own.</p>
	</div>
	<div class="main_card">
		<h2>Vision</h2>
		<p>Enable sustainability, eradicate poverty and create independency through local agribusiness.</p>
	</div>
	<div class="main_card">
		<h2>Contact us</h2>
		<p>Email: <a href="mailto:greengrocerfd@gmail.com">greengrocerfd@gmail.com</a></p>
		<p>Blog: <a href="https://greengrocerfoundation.wordpress.com/" target="_blank">https://greengrocerfoundation.wordpress.com/</a></p>
	</div>
	<!-- <img src="../statics/images/fogg-86.png" width="500px" alt=""> -->
{% endblock %}

app/templates/login.html
{% extends 'template.html' %}

{% block title %} Login {% endblock %}

{% block body %}
	<div class="auth">
		<form action="{{url_for('auth.login')}}" method="POST">
			<p><input required type="email" name="email" id="email" placeholder="Email"></p>
			<p><input required type="password" name="password" id="password" placeholder="Password"></p>
			<p><button>Login</button></p>
		</form>
		<div>
			<p>Do not have an account? <a href="{{url_for('auth.register')}}">Register</a></p>
			<p><a href="{{url_for('auth.register_business')}}">Start selling on GreenGrocer</a></p>
		</div>
	</div>
{% endblock %}

app/templates/products.html
{% extends 'template.html' %}

{% block title %} All products {% endblock %}

{% block body %}
	<form class="filter_search" action="{{url_for('main.products')}}" method="POST">
		<input type="search" name="keyword_search" placeholder="Type in a search keyword">
		<!-- <input type="number" name="cost_filter" id="cost_filter" placeholder="Enter cost in Ksh"> -->
		<select name="location_filter" id="location_filter">
			<option selected value="">Filter by location</option>
			{% for user in users%}
				{% if user.role == 'Seller' %}
					<option value="{{user.location}}">{{user.location}}</option>
				{% endif %}
			{% endfor %}
		</select>
		<select name="category_filter" id="category_filter">
			<option selected value="">Filter by category</option>
			<option value="animal">Animal products</option>
			<option value="plant">Plant products</option>
			<option value="equipments">Agricultural equipments</option>
		</select>
		<button class="filter">Search</button>
	</form>
	<div class="products">
		{% for product in products %}
			<div class="prod_cart">
				<h3>{{product.name}}</h3>
				<p class="prod_description">{{product.description}}</p>
				<h6>Unit price: {{product.price}}Ksh | Available: {% if product.quantity > 0 %}{{product.quantity}} {{product.unit}}{% else %}not available{% endif %}</h6>
				<form action="{{url_for('main.cart', id=product.id)}}", method="POST">
					{% if product.user_id != current_user.id %}
						<p><input type="number" name="quantity" required id="quantity" placeholder="Quantity"></p>
						<!-- <p><input class="hidden" type="text" name="product_id" disabled></p> -->
					{% endif %}
					<p>{% if product.user_id != current_user.id %}<button>Add to cart</button>{% endif %}</p>
				</form>
				<div class="owner_details">
					{% if product.user_id == current_user.id %}
						<p>From: You</p>
						<img src="{{product.user.avatar_hash}}" width="20px" alt="">
					{% else %}
						<p>From: {{product.user.name}}</p>
						<img src="{{product.user.avatar_hash}}" width="20px" alt="">
					{% endif %}
				</div>
			</div>
		{% endfor %}
	</div>
{% endblock %}

app/templates/register.html
{% extends 'template.html' %}

{% block title %} Register {% endblock %}

{% block body %}
	<div class="auth">
		<form action="{{url_for('auth.register')}}" method="POST"></p>
			<p><input type="name" name="name" id="name" placeholder="Name" required></p>
			<p><input type="email" name="email" id="email" placeholder="Email" required></p>
			<p><input type="password" name="password" id="password" placeholder="Password" required></p>
			<p><input type="password" name="repeat-password" id="repeat-password" placeholder="Repeat password" required></p>
			<p><input type="text" name="location" id="location" placeholder="Location" required></p>
			<p><input type="text" name="country" id="country" placeholder="Country" required></p>
			<p><button>Register</button></p>
		</form>
		<div>
			<p>Already have an account? <a href="{{url_for('auth.login')}}">Login</a></p>
			<p><a href="{{url_for('auth.register_business')}}">Start selling on GreenGrocer</a></p>
		</div>
	</div> 
{% endblock %}

app/templates/register_business.html
{% extends 'template.html' %}

{% block title %} Register business {% endblock %}

{% block body %}
	<div class="auth">
        <p><span class="independent">Independent Farmer</span><span class="company">Company</span></p>
		<form class="independent_form" action="{{url_for('auth.register_business')}}" method="POST"></p>
			<p><input required type="name" name="name" id="name" placeholder="Name"></p>
			<p><input required type="email" name="email" id="email" placeholder="Email"></p>
			<p><input required type="password" name="password" id="password" placeholder="Password"></p>
			<p><input required type="password" name="repeat-password" id="repeat-password" placeholder="Repeat password"></p>
			<p><input required type="text" name="location" id="location" placeholder="Location"></p>
			<p><input required type="text" name="country" id="country" placeholder="Country"></p>
			<select name="seller">
				<option selected value="independent">Independent</option>
			</select>
			<p><button>Register Business</button></p>
		</form>
        <form class="company_form hidden" action="{{url_for('auth.register_business')}}" method="POST"></p>
			<p><input required type="name" name="name" id="co_name" placeholder="Company name"></p>
			<p><input required type="email" name="email" id="co_email" placeholder="Contact email"></p>
			<p><input required type="text" name="co_number" id="co_number" placeholder="Company Reg Number"></p>
			<p><input required type="password" name="password" id="co_password" placeholder="Password"></p>
			<p><input required type="password" name="repeat-password" id="co_repeat-password" placeholder="Repeat password"></p>
			<p><input required type="text" name="location" id="co_location" placeholder="Location"></p>
			<p><input required type="text" name="country" id="co_country" placeholder="Country"></p>
			<select name="seller">
				<option selected value="company">Company</option>
			</select>
			<p><button>Register Company</button></p>
		</form>
		<div>
			<p>Already have an account? <a href="{{url_for('auth.login')}}">Login</a></p>
		</div>
	</div>
{% endblock %}

app/templates/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/statics/css/main.css">
    <link rel="shortcut icon" href="/statics/images/icons8-fast-cart-100.png" type="image/x-icon">
</head>
<body>
    <header>
        <div class="logo"><a href="{{url_for('main.home')}}">GreenGrocer</a></div>
        {% if current_user.is_authenticated %}
            <nav>
                <ul>
                    <a class="prod" href="{{url_for('main.home')}}"><li>Home</li></a>
                    <a class="prod" href="{{url_for('main.products')}}"><li>Products</li></a>
                    {% if current_user.role == 'Seller' %}
                        <a href="{{url_for('main.user_products', id=current_user.id)}}"><li>Your products</li></a>
                    {% endif %}
                    <a class="cart" href="{{url_for('main.cart', id=current_user.id)}}"><li><img src="/statics/images/icons8-fast-cart-100.png" alt="Cart" width="25px"></li><span>Cart</span></a>
                </ul>
            </nav>
            <div class="in-btn">
                <div>
                    <a href="{{url_for('auth.logout')}}"><button class="logout">Logout</button></a>
                    {% set name = current_user.name.split('|') %}
                    <button class="profile">{{name[0]}} </button>
                    <div class="profile-cart">
                        <ul>
                            <a href=""><li>Your profile</li></a>
                            <a href=""><li>Delete account</li></a>
                        </ul>
                    </div>
                </div>
                <img class="avatar" src="{{current_user.avatar_hash}}" width="40px" alt="User avatar">
            </div>
        {% else %}
            <div class="auth-btn">
                <a href="{{url_for('auth.login')}}"><button class="login">SignIn</button></a>
                <a href="{{url_for('auth.register')}}"><button class="register">Register</button></a>
            </div>
        {% endif %}
    </header>
    <main>
        <div class="main_wrapper">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <p class="flash_message">{{ message }} <span class="close_flash">&#x2715</span></p>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block body %}
            {% endblock %}
        </div>
    </main>
    <footer>
        <div class="container">
            <div class="motto">
                <p>&copy; GreenGrocer 2021</p>
                <p>-- We create a connection between farmers and potential buyers.</p>
            </div>
            <div class="terms">
                <a href="https://docs.google.com/document/d/1aShoUGBB29IuOPGBOOHB0Zh3oFfYYnu5hqMiy3xhl7M/edit?usp=sharing" target="_blank"><p>Terms and Conditions</p></a>
                <a href="https://docs.google.com/document/d/1aShoUGBB29IuOPGBOOHB0Zh3oFfYYnu5hqMiy3xhl7M/edit?usp=sharing" target="_blank"><p>Privacy Policy</p></a>
                <a href="{{url_for('auth.register_business')}}"><p>Become a Seller</p></a>
            </div>
            <div class="social">
                <a href=""><p>Twitter</p></a>
                <a href=""><p>Facebook</p></a>
                <a href=""><p>Instagram</p></a>
                <a href=""><p>LinkedIn</p></a>
            </div>
            <div class="letter">
                <p><input type="email" name="email" placeholder="Provide your email" required></p>
                <p><button disabled>Join our News Letter</button></p>
            </div>
            <p class="personal_quote">Designed&Implemented by <a href="mailto:murairicedric@gmail.com">Cédric Murairi</a</p>
        </div>
    </footer>
    <script src="/statics/javascript/index.js"></script>
</body>
</html>

app/templates/user_products.html
{% extends 'template.html' %}

{% block title %} Your products {% endblock %}

{% block body %}
	<h2 class="pr_h"><a href="{{url_for('main.add_product')}}"><button class="add_product_btn">Add a new product</button></a></h2>
	<div class="products">
		{% for product in products %}
			<div class="prod_cart">
				<h3>{{product.name}}</h3>
				<p class="prod_description">{{product.description}}</p>
				<h6>Unit price: {{product.price}}Ksh | Available: {% if product.quantity > 0 %}{{product.quantity}} {{product.unit}}{% else %}not available{% endif %}</h6>
				<p>
					<a href="{{url_for('main.remove_product', id=product.id)}}"><button>Remove product</button></a>
					<!-- <a href=""><button disabled>Edit product</button></a> -->
				</p>
			</div>
		{% endfor %}
	</div>
{% endblock %}